[package]
name = "oblivion"
version = "0.1.0"
edition = "2021"

[dependencies]

# for scrypt
hkdf = "0.12.4"
rand = "0.8.5"
ring = "0.17"
scrypt = "0.11.0"
sha2 = "0.10.8"

# for exception 
thiserror = "1"
